version: '3'
services:
  app:
    build: ./app # dockerfile and source code in path /app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    links:
      - db #host in archive database.yml
    depends_on:
      - db
    # necessary for use byebug
    stdin_open: true
    tty: true
  db:
    image: postgres
    restart: always
    volumes:
      - /database:/var/lib/postgresql/data
    ports:
      - "5432:5432"